### ISSUE TITLE
Name is not localization-safe

### ISSUE THREAD

**Issue by CptSpaceToaster** [GamedevGR/Archittack#1]
Because the name is written English, it would need to be translated into country-specific vernacular for proper localization.  This is too much effort, and this issue needs to be solved immediately!

I recommend we implement clever use of Emoji, and title our game using a cryptic symbol or two.  

That way, no one will understand the title, and we won't have to worry about proper language support.

The README.md should be updated to reflect this change.

**Comment by jacebrowning** [comment]
Spanish: Arquitaque
Frech: Archettaque
Chinese: 拱击
